import Anthropic from '@anthropic-ai/sdk';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const client = new Anthropic();
const MODEL = process.env.CLAUDE_MODEL || 'claude-sonnet-4-6';

const SYSTEM_PROMPT = `You are a senior product engineer and designer. Given a one-line product idea, you build a single-file, fully-realized, interactive HTML prototype.

Hard requirements:
- Output ONE complete HTML document. No commentary, no markdown fences, no preamble. Start with <!DOCTYPE html>.
- Inline ALL CSS in a <style> tag and ALL JS in <script> tags. No external files. No build step. No imports.
- You MAY load these CDN libraries via <script src=...> if useful: TailwindCSS (https://cdn.tailwindcss.com), Alpine.js, Chart.js, Three.js. Nothing else.
- The page must be genuinely functional, not a static mockup. If the idea is a todo app, the todos must add/complete/persist to localStorage. If it's a calculator, it must calculate. If it's a marketplace, items must be browsable and filterable with seeded sample data.
- Use modern, beautiful design: thoughtful typography, generous whitespace, real color palette (not default grays), micro-interactions, responsive layout. Mobile-first.
- Seed realistic sample data so the prototype feels alive on first load.
- Include a small footer line: "Prototype generated by Claude from a single text message." — keep it understated.
- Do not include analytics, tracking pixels, or external API calls.
- Accessibility: semantic HTML, alt text, focus styles, contrast.
- Do not invent URLs, claim partnerships, or use third-party trademarks as logos.

Length budget: aim for 800-2500 lines of meaningful, working code. Better to ship a tight working prototype than a sprawling broken one.`;

/**
 * Ask Claude to generate the full HTML for the prototype.
 * Returns the raw HTML string.
 */
export async function generateSite({ idea, slug }) {
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error('ANTHROPIC_API_KEY is not set');
  }

  const userPrompt = `Build a working interactive HTML prototype for this idea:

"${idea}"

The prototype will be served at https://openaitpm.com/${slug}

Make it feel like a real product someone could demo. Output only the HTML document.`;

  const resp = await client.messages.create({
    model: MODEL,
    max_tokens: 16000,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const text = resp.content
    .filter(b => b.type === 'text')
    .map(b => b.text)
    .join('');

  return sanitizeHtml(text);
}

/**
 * Generate + persist to disk under sitesDir/<slug>/index.html.
 * Also writes meta.json with the original idea and timestamp.
 */
export async function generateAndSave({ idea, slug, sitesDir, from }) {
  const html = await generateSite({ idea, slug });
  const dir = join(sitesDir, slug);
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, 'index.html'), html, 'utf8');
  await writeFile(
    join(dir, 'meta.json'),
    JSON.stringify({ idea, slug, from: from || null, createdAt: new Date().toISOString() }, null, 2),
    'utf8'
  );
  return { slug, dir, bytes: Buffer.byteLength(html, 'utf8') };
}

function sanitizeHtml(text) {
  let html = text.trim();

  // Strip a leading ```html ... ``` fence if Claude slipped one in despite the prompt.
  const fence = /^```(?:html)?\s*\n([\s\S]*?)\n```\s*$/i;
  const m = html.match(fence);
  if (m) html = m[1].trim();

  // If output doesn't start with a doctype/html tag, wrap it minimally so we never
  // serve a fragment that breaks the page.
  if (!/^<!doctype html/i.test(html) && !/^<html/i.test(html)) {
    html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Prototype</title></head><body>${html}</body></html>`;
  }
  return html;
}
